"""
API routes for column hints management.
Provides CRUD operations, search, versioning, and LLM generation.
"""

from fastapi import APIRouter, HTTPException, Body
from pydantic import BaseModel, Field
from typing import Dict, List, Any, Optional
import logging

from kg_builder.services.hint_manager import get_hint_manager
from kg_builder.services.llm_service import get_llm_service

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/hints", tags=["hints"])


# ==================== Pydantic Models ====================

class ColumnHint(BaseModel):
    """Model for column hint data."""
    business_name: str = Field(..., description="Human-friendly name")
    aliases: List[str] = Field(default_factory=list, description="Alternative names")
    description: str = Field(default="", description="What this column represents")
    semantic_type: str = Field(default="attribute", description="identifier|measure|dimension|date|flag")
    data_type: Optional[str] = Field(None, description="SQL data type")
    role: str = Field(default="attribute", description="primary_key|foreign_key|attribute")
    common_terms: List[str] = Field(default_factory=list, description="How users ask for this")
    examples: List[str] = Field(default_factory=list, description="Sample values")
    allowed_values: Optional[List[str]] = Field(None, description="Valid values if enum")
    searchable: bool = Field(default=True, description="Can be searched")
    filterable: bool = Field(default=True, description="Can be filtered")
    aggregatable: bool = Field(default=False, description="Can be aggregated")
    priority: str = Field(default="medium", description="high|medium|low")
    default_filter: Optional[str] = Field(None, description="Default filter value")
    business_rules: List[str] = Field(default_factory=list, description="Business rules")
    user_notes: str = Field(default="", description="User notes")
    auto_generated: bool = Field(default=False, description="Generated by LLM")
    manual_verified: bool = Field(default=False, description="Verified by user")


class TableHint(BaseModel):
    """Model for table hint data."""
    business_name: str = Field(..., description="Human-friendly table name")
    aliases: List[str] = Field(default_factory=list, description="Alternative names")
    description: str = Field(default="", description="What this table represents")
    category: str = Field(default="", description="master_data|transaction|reference")
    user_notes: str = Field(default="", description="User notes")


class UpdateColumnHintRequest(BaseModel):
    """Request to update a column hint."""
    table_name: str
    column_name: str
    hints: ColumnHint
    user: str = "anonymous"


class UpdateTableHintRequest(BaseModel):
    """Request to update a table hint."""
    table_name: str
    hints: TableHint
    user: str = "anonymous"


class DeleteHintRequest(BaseModel):
    """Request to delete hints."""
    table_name: str
    column_name: Optional[str] = None
    user: str = "anonymous"


class SearchHintsRequest(BaseModel):
    """Request to search hints."""
    search_term: str
    limit: int = 10


class CreateVersionRequest(BaseModel):
    """Request to create a version snapshot."""
    version_name: str
    user: str = "anonymous"
    comment: str = ""


class GenerateHintsRequest(BaseModel):
    """Request to generate hints using LLM."""
    table_name: str
    column_name: str
    column_type: str
    sample_values: Optional[List[str]] = None
    table_context: Optional[str] = None
    user: str = "anonymous"


class BulkGenerateHintsRequest(BaseModel):
    """Request to generate hints for all columns in a table."""
    table_name: str
    schema_path: str = "schemas/newdqschemanov.json"
    user: str = "anonymous"
    overwrite_existing: bool = False


# ==================== API Endpoints ====================

@router.get("/")
async def get_all_hints():
    """
    Get all hints dictionary.

    Returns:
        Complete hints structure with all tables and columns
    """
    try:
        hint_manager = get_hint_manager()
        hints = hint_manager.load_hints()
        return {
            "success": True,
            "data": hints
        }
    except Exception as e:
        logger.error(f"Error getting all hints: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/statistics")
async def get_hints_statistics():
    """
    Get statistics about the hints dictionary.

    Returns:
        Statistics including totals, auto-generated count, etc.
    """
    try:
        hint_manager = get_hint_manager()
        stats = hint_manager.get_statistics()
        return {
            "success": True,
            "data": stats
        }
    except Exception as e:
        logger.error(f"Error getting statistics: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/table/{table_name}")
async def get_table_hints(table_name: str):
    """
    Get hints for a specific table.

    Args:
        table_name: Name of the table

    Returns:
        Table hints including table-level and all column hints
    """
    try:
        hint_manager = get_hint_manager()
        hints = hint_manager.get_table_hints(table_name)

        if hints is None:
            raise HTTPException(status_code=404, detail=f"Table '{table_name}' not found")

        return {
            "success": True,
            "data": hints
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error getting table hints: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/column/{table_name}/{column_name}")
async def get_column_hints(table_name: str, column_name: str):
    """
    Get hints for a specific column.

    Args:
        table_name: Name of the table
        column_name: Name of the column

    Returns:
        Column hints
    """
    try:
        hint_manager = get_hint_manager()
        hints = hint_manager.get_column_hints(table_name, column_name)

        if hints is None:
            raise HTTPException(
                status_code=404,
                detail=f"Column '{table_name}.{column_name}' not found"
            )

        return {
            "success": True,
            "data": hints
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error getting column hints: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/table")
async def update_table_hints(request: UpdateTableHintRequest):
    """
    Add or update hints for a table.

    Args:
        request: Table hint update request

    Returns:
        Success confirmation
    """
    try:
        hint_manager = get_hint_manager()
        hint_manager.add_table_hints(
            table_name=request.table_name,
            table_hints=request.hints.dict(),
            user=request.user
        )

        return {
            "success": True,
            "message": f"Table hints updated for '{request.table_name}'"
        }
    except Exception as e:
        logger.error(f"Error updating table hints: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/column")
async def update_column_hints(request: UpdateColumnHintRequest):
    """
    Add or update hints for a column.

    Args:
        request: Column hint update request

    Returns:
        Success confirmation
    """
    try:
        hint_manager = get_hint_manager()
        hint_manager.add_column_hints(
            table_name=request.table_name,
            column_name=request.column_name,
            column_hints=request.hints.dict(),
            user=request.user
        )

        return {
            "success": True,
            "message": f"Column hints updated for '{request.table_name}.{request.column_name}'"
        }
    except Exception as e:
        logger.error(f"Error updating column hints: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.patch("/column/{table_name}/{column_name}/{field_name}")
async def update_column_hint_field(
    table_name: str,
    column_name: str,
    field_name: str,
    field_value: Any = Body(...),
    user: str = Body(default="anonymous")
):
    """
    Update a single field in column hints.

    Args:
        table_name: Name of the table
        column_name: Name of the column
        field_name: Field to update (e.g., 'business_name', 'aliases')
        field_value: New value for the field
        user: User making the change

    Returns:
        Success confirmation
    """
    try:
        hint_manager = get_hint_manager()
        hint_manager.update_column_hint_field(
            table_name=table_name,
            column_name=column_name,
            field_name=field_name,
            field_value=field_value,
            user=user
        )

        return {
            "success": True,
            "message": f"Updated {field_name} for '{table_name}.{column_name}'"
        }
    except Exception as e:
        logger.error(f"Error updating column hint field: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.delete("/hints")
async def delete_hints(request: DeleteHintRequest):
    """
    Delete hints for a table or column.

    Args:
        request: Delete request with table and optional column name

    Returns:
        Success confirmation
    """
    try:
        hint_manager = get_hint_manager()

        if request.column_name:
            # Delete column hints
            success = hint_manager.delete_column_hints(
                table_name=request.table_name,
                column_name=request.column_name,
                user=request.user
            )
            target = f"column '{request.table_name}.{request.column_name}'"
        else:
            # Delete table hints
            success = hint_manager.delete_table_hints(
                table_name=request.table_name,
                user=request.user
            )
            target = f"table '{request.table_name}'"

        if not success:
            raise HTTPException(status_code=404, detail=f"Hints not found for {target}")

        return {
            "success": True,
            "message": f"Deleted hints for {target}"
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error deleting hints: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/search")
async def search_hints(request: SearchHintsRequest):
    """
    Search for columns by business name, aliases, or common terms.

    Args:
        request: Search request with search term

    Returns:
        List of matching columns with their hints
    """
    try:
        hint_manager = get_hint_manager()
        results = hint_manager.search_hints(request.search_term)

        # Limit results
        limited_results = results[:request.limit]

        return {
            "success": True,
            "data": limited_results,
            "total_found": len(results),
            "returned": len(limited_results)
        }
    except Exception as e:
        logger.error(f"Error searching hints: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/version")
async def create_version(request: CreateVersionRequest):
    """
    Create a versioned snapshot of current hints.

    Args:
        request: Version creation request

    Returns:
        Success confirmation
    """
    try:
        hint_manager = get_hint_manager()
        hint_manager.create_version_snapshot(
            version_name=request.version_name,
            user=request.user,
            comment=request.comment
        )

        return {
            "success": True,
            "message": f"Created version snapshot: {request.version_name}"
        }
    except Exception as e:
        logger.error(f"Error creating version: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/generate")
async def generate_column_hints(request: GenerateHintsRequest):
    """
    Generate hints for a column using LLM.

    Args:
        request: Hint generation request

    Returns:
        Generated hints
    """
    try:
        llm_service = get_llm_service()

        if not llm_service.is_enabled():
            raise HTTPException(
                status_code=503,
                detail="LLM service is not available"
            )

        # Generate hints using LLM
        result = llm_service.extract_column_hints(
            table_name=request.table_name,
            column_name=request.column_name,
            column_type=request.column_type,
            sample_values=request.sample_values,
            table_context=request.table_context
        )

        if 'error' in result:
            raise HTTPException(status_code=500, detail=result['error'])

        # Save generated hints
        hint_manager = get_hint_manager()
        hints_data = result.get('hints', {})
        hints_data['auto_generated'] = True
        hints_data['data_type'] = request.column_type

        hint_manager.add_column_hints(
            table_name=request.table_name,
            column_name=request.column_name,
            column_hints=hints_data,
            user=request.user
        )

        return {
            "success": True,
            "message": "Hints generated and saved",
            "data": result
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error generating hints: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/generate/bulk")
async def bulk_generate_hints(request: BulkGenerateHintsRequest):
    """
    Generate hints for all columns in a table using LLM.

    Args:
        request: Bulk generation request

    Returns:
        Summary of generated hints
    """
    try:
        import json
        from pathlib import Path

        llm_service = get_llm_service()
        hint_manager = get_hint_manager()

        if not llm_service.is_enabled():
            raise HTTPException(
                status_code=503,
                detail="LLM service is not available"
            )

        # Load schema
        schema_path = Path(request.schema_path)
        if not schema_path.exists():
            raise HTTPException(status_code=404, detail=f"Schema file not found: {request.schema_path}")

        with open(schema_path, 'r', encoding='utf-8') as f:
            schema = json.load(f)

        # Get table info
        table_info = schema.get('tables', {}).get(request.table_name)
        if not table_info:
            raise HTTPException(status_code=404, detail=f"Table '{request.table_name}' not found in schema")

        # Generate hints for each column
        generated_count = 0
        skipped_count = 0
        errors = []

        for column in table_info.get('columns', []):
            column_name = column['name']
            column_type = column.get('type', 'UNKNOWN')

            # Skip if already exists and overwrite is False
            if not request.overwrite_existing:
                existing = hint_manager.get_column_hints(request.table_name, column_name)
                if existing:
                    skipped_count += 1
                    continue

            try:
                # Generate hints
                result = llm_service.extract_column_hints(
                    table_name=request.table_name,
                    column_name=column_name,
                    column_type=column_type
                )

                # Save hints
                hints_data = result.get('hints', {})
                hints_data['auto_generated'] = True
                hints_data['data_type'] = column_type

                hint_manager.add_column_hints(
                    table_name=request.table_name,
                    column_name=column_name,
                    column_hints=hints_data,
                    user=request.user
                )

                generated_count += 1

            except Exception as e:
                logger.error(f"Error generating hints for {column_name}: {e}")
                errors.append(f"{column_name}: {str(e)}")

        return {
            "success": True,
            "message": f"Bulk generation completed for table '{request.table_name}'",
            "data": {
                "table_name": request.table_name,
                "total_columns": len(table_info.get('columns', [])),
                "generated": generated_count,
                "skipped": skipped_count,
                "errors": errors
            }
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error in bulk generation: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/export")
async def export_hints(output_path: str = "schemas/hints/column_hints_export.json"):
    """
    Export hints to a file.

    Args:
        output_path: Path to export file

    Returns:
        Success confirmation
    """
    try:
        hint_manager = get_hint_manager()
        hint_manager.export_hints(output_path)

        return {
            "success": True,
            "message": f"Hints exported to: {output_path}"
        }
    except Exception as e:
        logger.error(f"Error exporting hints: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/import")
async def import_hints(
    input_path: str = Body(...),
    merge: bool = Body(default=False),
    user: str = Body(default="anonymous")
):
    """
    Import hints from a file.

    Args:
        input_path: Path to hints file to import
        merge: If True, merge with existing; if False, replace
        user: User performing the import

    Returns:
        Success confirmation
    """
    try:
        from pathlib import Path

        if not Path(input_path).exists():
            raise HTTPException(status_code=404, detail=f"Import file not found: {input_path}")

        hint_manager = get_hint_manager()
        hint_manager.import_hints(input_path, merge=merge, user=user)

        action = "merged" if merge else "replaced"
        return {
            "success": True,
            "message": f"Hints {action} from: {input_path}"
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error importing hints: {e}")
        raise HTTPException(status_code=500, detail=str(e))
