-- =====================================================
-- FIX: brz_lnd_IBP_Product_Master PRDID Matching Logic
-- Some records match MATERIAL, some don't (for testing)
-- =====================================================

SET NOCOUNT ON;

PRINT 'Fixing brz_lnd_IBP_Product_Master PRDID matching logic...';

-- Clear and repopulate with correct PRDID logic
TRUNCATE TABLE brz_lnd_IBP_Product_Master;

INSERT INTO brz_lnd_IBP_Product_Master (
    field1, SCNID, PRDID, UOMID, ZBASEMATERIAL, ZBOM1TXT, ZBOM1,
    ZBOM1QTYPER, ZBOM2, ZBOM2QTYPER, ZBOM3, ZBOM3QTYPER, ZBOM4, ZBOM4QTYPER,
    ZBUILDPACKOUT, ZBUSUNIT, ZPRDFAMILY, ZMATGRP, ZCODERELEVANT, ZCONSTRAINTHORIZON,
    ZCOOLINGTYPE, ZCRITICALPRODUCT, ZXPLANTSTATUS, ZDEMANDGROUP, ZDEVICECAT,
    ZDIEBIN, ZDIERBPINDICATOR, ZDIEREVLVL, ZDIRECTPOST, ZDRIVERSKU,
    ZDTKDESC, ZFAB, ZFABTECH, ZGPU1, ZGPU1QTYPER, ZGPU2, ZGPU2QTYPER,
    ZMAKEBUY, ZMATTYPE, ZITEMGRP, ZMARKTNAME, ZITMPRIORITYTIER, ZITEMTECH,
    ZJFFMKTNAME, ZRBPITGP, ZKITPRODUCT, ZLIFECYCLESTATE, PRODGROUP, PRODTYPE,
    ZPRIMARYMEMORY1, ZMEMORY1QTYPER, ZMEMORY2, ZMEMORY2QTYPER, ZMOQ2, ZMOQ1,
    ZRBPNOTES3, ZOLDMAT, ZACTIVEINACTIVE, ZOPSPCB, ZPLANNER, ZPLCCODE,
    PRODDESC, ZPRODUCTFLAG1, ZPRDGROUP, PRODUCTHIERARCHY, ZPRDUCTLINE, ZPRDLNEDESC,
    PRODUCTDEL, ZRBPNOTES1, ZPROFITCENTER, ZPROGCODE, ZRBPPLANNER, ZMARKETCODE,
    ZRBPNOTES2, SHELFLIFEACTIVE, ZSNPPLNR, ZSORTPRIORITYINT, ZSUBFMLY,
    ZSYSTEMDIRECTBUILD, ZTKLEADTIME, ZTKMANUFACTURER, ZTKMANUFACTPARTNUM, ZTKUNITCOST,
    ZTOPLVLNAME, ZVIRTUALKIT, LASTMODIFIEDBY, LASTMODIFIEDDATE, CREATEDBY, CREATEDDATE
)
SELECT 
    -- field1 (NVARCHAR(5))
    CASE [Product Type] WHEN N'GPU' THEN N'GPU' ELSE N'NBU' END,
    
    -- SCNID (NVARCHAR(12))
    N'SCN' + RIGHT(N'000000' + CAST(ROW_NUMBER() OVER (ORDER BY MATERIAL) AS NVARCHAR), 6),
    
    -- PRDID (NVARCHAR(31)) - KEY LOGIC: Mix of matching and non-matching
    CASE 
        -- 70% of records: EXACT MATCH with MATERIAL (for relationship testing)
        WHEN (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 10) <= 6 THEN MATERIAL
        
        -- 20% of records: PREFIX MATCH (PRD_ + MATERIAL for hierarchical testing)  
        WHEN (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 10) IN (7, 8) THEN N'PRD_' + MATERIAL
        
        -- 10% of records: NO MATCH (completely different values for negative testing)
        ELSE N'NOMATCH_' + CAST(ROW_NUMBER() OVER (ORDER BY MATERIAL) + 9000 AS NVARCHAR)
    END,
    
    -- UOMID (NVARCHAR(9))
    CASE [Product Type] WHEN N'GPU' THEN N'EA' ELSE N'PC' END,
    
    -- ZBASEMATERIAL (NVARCHAR(34)) - Always matches MATERIAL exactly
    MATERIAL,
    
    -- ZBOM1TXT (NVARCHAR(40))
    CASE [Product Type] WHEN N'GPU' THEN N'GPU Die Silicon' ELSE N'Processing Core' END,
    
    -- ZBOM1 (NVARCHAR(18))
    N'B1_' + RIGHT(MATERIAL, 13),
    
    -- ZBOM1QTYPER (NVARCHAR(12))
    N'1.000',
    
    -- ZBOM2 (NVARCHAR(18))
    N'B2_' + RIGHT(MATERIAL, 13),
    
    -- ZBOM2QTYPER (NVARCHAR(12))
    N'2.000',
    
    -- ZBOM3 (NVARCHAR(9))
    N'B3_' + RIGHT(MATERIAL, 4),
    
    -- ZBOM3QTYPER (NVARCHAR(12))
    N'1.000',
    
    -- ZBOM4 (NVARCHAR(18))
    N'B4_' + RIGHT(MATERIAL, 13),
    
    -- ZBOM4QTYPER (NVARCHAR(12))
    N'1.000',
    
    -- ZBUILDPACKOUT (NVARCHAR(16))
    CASE [Product Type] WHEN N'GPU' THEN N'GPU_BUILD' ELSE N'NBU_BUILD' END,
    
    -- ZBUSUNIT (NVARCHAR(13))
    CASE [Product Type] WHEN N'GPU' THEN N'GPUBU' ELSE N'NBUBU' END,
    
    -- ZPRDFAMILY (NVARCHAR(19))
    CASE [Product Type] WHEN N'GPU' THEN N'GPU_FAM_' + CAST((ROW_NUMBER() OVER (ORDER BY MATERIAL) % 4) + 1 AS NVARCHAR) ELSE N'NBU_FAM_' + CAST((ROW_NUMBER() OVER (ORDER BY MATERIAL) % 3) + 1 AS NVARCHAR) END,
    
    -- ZMATGRP (NVARCHAR(18))
    CASE [Product Type] WHEN N'GPU' THEN N'GPU_MAT_GRP' ELSE N'NBU_MAT_GRP' END,
    
    -- ZCODERELEVANT (NVARCHAR(13))
    CASE (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 2) WHEN 0 THEN N'YES' ELSE N'NO' END,
    
    -- ZCONSTRAINTHORIZON (NVARCHAR(18))
    N'HORIZON_' + CAST((ROW_NUMBER() OVER (ORDER BY MATERIAL) % 12) + 1 AS NVARCHAR),
    
    -- ZCOOLINGTYPE (NVARCHAR(12))
    CASE [Product Type] WHEN N'GPU' THEN CASE (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 3) WHEN 0 THEN N'AIR' WHEN 1 THEN N'LIQUID' ELSE N'HYBRID' END ELSE N'PASSIVE' END,
    
    -- ZCRITICALPRODUCT (NVARCHAR(16))
    CASE (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 3) WHEN 0 THEN N'CRITICAL' WHEN 1 THEN N'HIGH_PRIORITY' ELSE N'STANDARD' END,
    
    -- ZXPLANTSTATUS (NVARCHAR(27))
    CASE (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 4) WHEN 0 THEN N'ACTIVE_PRODUCTION' WHEN 1 THEN N'RAMP_UP' WHEN 2 THEN N'PHASE_OUT' ELSE N'MAINTENANCE' END,
    
    -- ZDEMANDGROUP (NVARCHAR(25))
    CASE [Product Type] WHEN N'GPU' THEN N'GPU_DEMAND_' + CAST((ROW_NUMBER() OVER (ORDER BY MATERIAL) % 3) + 1 AS NVARCHAR) ELSE N'NBU_DEMAND_' + CAST((ROW_NUMBER() OVER (ORDER BY MATERIAL) % 2) + 1 AS NVARCHAR) END,
    
    -- ZDEVICECAT (NVARCHAR(15))
    CASE [Product Type] WHEN N'GPU' THEN N'GRAPHICS_CARD' ELSE N'EDGE_DEVICE' END,
    
    -- ZDIEBIN (NVARCHAR(7))
    N'BIN' + RIGHT(MATERIAL, 3),
    
    -- ZDIERBPINDICATOR (NVARCHAR(17))
    CASE (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 2) WHEN 0 THEN N'RBP_ACTIVE' ELSE N'RBP_INACTIVE' END,
    
    -- ZDIEREVLVL (NVARCHAR(18))
    N'REV_' + CASE (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 5) WHEN 0 THEN N'A0' WHEN 1 THEN N'A1' WHEN 2 THEN N'B0' WHEN 3 THEN N'B1' ELSE N'C0' END,
    
    -- ZDIRECTPOST (NVARCHAR(19))
    CASE (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 2) WHEN 0 THEN N'DIRECT_POST_YES' ELSE N'DIRECT_POST_NO' END,
    
    -- ZDRIVERSKU (NVARCHAR(10))
    N'DRV' + RIGHT(MATERIAL, 6),
    
    -- ZDTKDESC (NVARCHAR(18)) - FIXED LENGTH
    CASE [Product Type] WHEN N'GPU' THEN N'GPU Desktop Card' ELSE N'NBU Edge Device' END,
    
    -- ZFAB (NVARCHAR(4))
    CASE (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 4) WHEN 0 THEN N'FAB1' WHEN 1 THEN N'FAB2' WHEN 2 THEN N'FAB3' ELSE N'FAB4' END,
    
    -- ZFABTECH (NVARCHAR(14))
    CASE [Product Type] WHEN N'GPU' THEN CASE (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 3) WHEN 0 THEN N'5NM' WHEN 1 THEN N'7NM' ELSE N'4NM' END ELSE CASE (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 2) WHEN 0 THEN N'7NM' ELSE N'5NM' END END,
    
    -- ZGPU1 (NVARCHAR(18))
    CASE [Product Type] WHEN N'GPU' THEN N'G1_' + RIGHT(MATERIAL, 14) ELSE NULL END,
    
    -- ZGPU1QTYPER (NVARCHAR(13))
    CASE [Product Type] WHEN N'GPU' THEN N'1.000' ELSE NULL END,
    
    -- ZGPU2 (NVARCHAR(18))
    CASE [Product Type] WHEN N'GPU' THEN N'G2_' + RIGHT(MATERIAL, 14) ELSE NULL END,
    
    -- ZGPU2QTYPER (NVARCHAR(13))
    CASE [Product Type] WHEN N'GPU' THEN N'0.000' ELSE NULL END,
    
    -- Continue with remaining columns (shortened for brevity)
    CASE (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 3) WHEN 0 THEN N'M' WHEN 1 THEN N'B' ELSE N'C' END, -- ZMAKEBUY
    CASE [Product Type] WHEN N'GPU' THEN N'FERT' ELSE N'HALB' END, -- ZMATTYPE
    CASE [Product Type] WHEN N'GPU' THEN N'GPU Item Group' ELSE N'NBU Item Group' END, -- ZITEMGRP (40 chars max)
    CASE [Product Type] WHEN N'GPU' THEN N'GPU Mkt ' + CAST(ROW_NUMBER() OVER (ORDER BY MATERIAL) AS NVARCHAR) ELSE N'NBU Mkt ' + CAST(ROW_NUMBER() OVER (ORDER BY MATERIAL) AS NVARCHAR) END, -- ZMARKTNAME (40 chars max)
    CASE (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 4) WHEN 0 THEN N'TIER_1_CRITICAL' WHEN 1 THEN N'TIER_2_HIGH' WHEN 2 THEN N'TIER_3_MEDIUM' ELSE N'TIER_4_LOW' END, -- ZITMPRIORITYTIER
    CASE [Product Type] WHEN N'GPU' THEN N'GPU_TECH' ELSE N'NBU_TECH' END, -- ZITEMTECH
    CASE [Product Type] WHEN N'GPU' THEN N'JFF GPU ' + CAST(ROW_NUMBER() OVER (ORDER BY MATERIAL) AS NVARCHAR) ELSE N'JFF NBU ' + CAST(ROW_NUMBER() OVER (ORDER BY MATERIAL) AS NVARCHAR) END, -- ZJFFMKTNAME (38 chars max)
    CASE [Product Type] WHEN N'GPU' THEN N'RBP GPU ' + CAST(ROW_NUMBER() OVER (ORDER BY MATERIAL) AS NVARCHAR) ELSE N'RBP NBU ' + CAST(ROW_NUMBER() OVER (ORDER BY MATERIAL) AS NVARCHAR) END, -- ZRBPITGP (38 chars max)
    CASE (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 3) WHEN 0 THEN N'KIT_PRODUCT' WHEN 1 THEN N'SINGLE_ITEM' ELSE N'BUNDLE' END, -- ZKITPRODUCT
    CASE (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 5) WHEN 0 THEN N'INTRODUCTION' WHEN 1 THEN N'GROWTH' WHEN 2 THEN N'MATURITY' WHEN 3 THEN N'DECLINE' ELSE N'SUSTAIN' END, -- ZLIFECYCLESTATE
    CASE [Product Type] WHEN N'GPU' THEN N'Graphics' ELSE N'Network' END, -- PRODGROUP (14 chars max)
    [Product Type], -- PRODTYPE
    CASE [Product Type] WHEN N'GPU' THEN N'MEM1_' + RIGHT(MATERIAL, 8) ELSE NULL END, -- ZPRIMARYMEMORY1 (15 chars max)
    CASE [Product Type] WHEN N'GPU' THEN CAST((ROW_NUMBER() OVER (ORDER BY MATERIAL) % 8) + 1 AS NVARCHAR) + N'.000' ELSE NULL END, -- ZMEMORY1QTYPER
    CASE [Product Type] WHEN N'GPU' THEN N'MEM2_' + RIGHT(MATERIAL, 5) ELSE NULL END, -- ZMEMORY2 (12 chars max)
    CASE [Product Type] WHEN N'GPU' THEN N'0.000' ELSE NULL END, -- ZMEMORY2QTYPER
    CAST(100 + (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 900) AS NVARCHAR), -- ZMOQ2 (15 chars max)
    CAST(50 + (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 49) AS NVARCHAR), -- ZMOQ1 (5 chars max)
    N'RBP3: ' + RIGHT(MATERIAL, 26), -- ZRBPNOTES3 (34 chars max)
    CASE (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 10) WHEN 0 THEN N'OLD_' + RIGHT(MATERIAL, 7) ELSE NULL END, -- ZOLDMAT (12 chars max)
    CASE OPS_STATUS WHEN N'ACTIVE' THEN N'ACTIVE' WHEN N'NEW_PRODUCT' THEN N'ACTIVE' ELSE N'INACTIVE' END, -- ZACTIVEINACTIVE
    N'PCB' + RIGHT(MATERIAL, 3), -- ZOPSPCB (7 chars max)
    LEFT(OPS_PLANNER, 21), -- ZPLANNER (21 chars max)
    LEFT(OPS_PLCCODE, 21), -- ZPLCCODE (21 chars max)
    CASE [Product Type] WHEN N'GPU' THEN N'High Performance Graphics Unit' ELSE N'Advanced Network Processing Unit' END, -- PRODDESC (40 chars max)
    CASE (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 3) WHEN 0 THEN N'FLAG_PREMIUM' WHEN 1 THEN N'FLAG_STANDARD' ELSE N'FLAG_VALUE' END, -- ZPRODUCTFLAG1
    LEFT(PRODGRP_CP, 13), -- ZPRDGROUP (13 chars max)
    N'HIER_' + CASE [Product Type] WHEN N'GPU' THEN N'GPU' ELSE N'NBU' END + N'_' + CAST(ROW_NUMBER() OVER (ORDER BY MATERIAL) AS NVARCHAR), -- PRODUCTHIERARCHY (18 chars max)
    [Product Line], -- ZPRDUCTLINE
    CASE [Product Line] WHEN N'RTXGP' THEN N'RTX Graphics' WHEN N'GTXGP' THEN N'GTX Graphics' WHEN N'QUADR' THEN N'Quadro Pro' WHEN N'TESLA' THEN N'Tesla Compute' WHEN N'DRIVE' THEN N'DRIVE Auto' WHEN N'JETSO' THEN N'Jetson Edge AI' ELSE N'Orin Computing' END, -- ZPRDLNEDESC (24 chars max)
    CASE (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 20) WHEN 0 THEN N'X' ELSE NULL END, -- PRODUCTDEL
    N'RBP1: ' + RIGHT(MATERIAL, 7), -- ZRBPNOTES1 (15 chars max)
    CASE [Product Type] WHEN N'GPU' THEN N'PC_GPU_' + CAST((ROW_NUMBER() OVER (ORDER BY MATERIAL) % 5) + 1 AS NVARCHAR) ELSE N'PC_NBU_' + CAST((ROW_NUMBER() OVER (ORDER BY MATERIAL) % 3) + 1 AS NVARCHAR) END, -- ZPROFITCENTER (13 chars max)
    N'PROG_' + CASE [Product Type] WHEN N'GPU' THEN N'GPU' ELSE N'NBU' END + N'_' + CAST(ROW_NUMBER() OVER (ORDER BY MATERIAL) AS NVARCHAR), -- ZPROGCODE (20 chars max)
    N'RBP: ' + LEFT(OPS_PLANNER, 13), -- ZRBPPLANNER (19 chars max)
    CASE [Product Type]
        WHEN N'GPU' THEN 
            CASE (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 6)
                WHEN 0 THEN N'MKT_GPU_GAMING_CONSUMER_NA_HIGH_END'
                WHEN 1 THEN N'MKT_GPU_PROFESSIONAL_WORKSTATION_EMEA'
                WHEN 2 THEN N'MKT_GPU_DATACENTER_AI_APAC_ENTERPRISE'
                WHEN 3 THEN N'MKT_GPU_AUTOMOTIVE_EMBEDDED_GLOBAL'
                WHEN 4 THEN N'MKT_GPU_CRYPTO_MINING_LATAM_VOLUME'
                ELSE N'MKT_GPU_EDGE_COMPUTING_MEA_SPECIALTY'
            END
        ELSE 
            CASE (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 4)
                WHEN 0 THEN N'MKT_NBU_EDGE_AI_ROBOTICS_GLOBAL_PREMIUM'
                WHEN 1 THEN N'MKT_NBU_AUTOMOTIVE_AUTONOMOUS_NA_TIER1'
                WHEN 2 THEN N'MKT_NBU_INDUSTRIAL_IOT_EMEA_STANDARD'
                ELSE N'MKT_NBU_HEALTHCARE_MEDICAL_APAC_CRITICAL'
            END
    END, -- ZMARKETCODE (43 chars max)
    N'RBP2: ' + RIGHT(MATERIAL, 18), -- ZRBPNOTES2 (26 chars max)
    CASE (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 2) WHEN 0 THEN N'ACTIVE' ELSE N'INACTIVE' END, -- SHELFLIFEACTIVE
    N'SNP: ' + LEFT(OPS_PLANNER, 5), -- ZSNPPLNR (11 chars max)
    CAST((ROW_NUMBER() OVER (ORDER BY MATERIAL) % 1000) + 1 AS NVARCHAR), -- ZSORTPRIORITYINT
    CASE [Product Type] WHEN N'GPU' THEN N'GPU_SUB_' + CAST((ROW_NUMBER() OVER (ORDER BY MATERIAL) % 5) + 1 AS NVARCHAR) ELSE N'NBU_SUB_' + CAST((ROW_NUMBER() OVER (ORDER BY MATERIAL) % 3) + 1 AS NVARCHAR) END, -- ZSUBFMLY (17 chars max)
    CASE (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 2) WHEN 0 THEN N'DIRECT_BUILD_YES' ELSE N'DIRECT_BUILD_NO' END, -- ZSYSTEMDIRECTBUILD (20 chars max)
    CAST(30 + (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 60) AS NVARCHAR), -- ZTKLEADTIME
    CASE (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 5) WHEN 0 THEN N'TSMC Taiwan Semiconductor' WHEN 1 THEN N'Samsung Foundry Korea' WHEN 2 THEN N'GlobalFoundries Malta' WHEN 3 THEN N'Intel Foundry Services' ELSE N'SK Hynix Memory Solutions' END, -- ZTKMANUFACTURER (30 chars max)
    N'MPN_' + MATERIAL + N'_' + CAST(ROW_NUMBER() OVER (ORDER BY MATERIAL) AS NVARCHAR), -- ZTKMANUFACTPARTNUM (30 chars max)
    CASE [Product Type] WHEN N'GPU' THEN CAST(200 + (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 800) AS NVARCHAR) + N'.00' ELSE CAST(100 + (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 400) AS NVARCHAR) + N'.00' END, -- ZTKUNITCOST
    CASE [Product Type]
        WHEN N'GPU' THEN 
            CASE (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 5)
                WHEN 0 THEN N'NVIDIA GeForce RTX Gaming Graphics'
                WHEN 1 THEN N'NVIDIA Quadro Professional Workstation'
                WHEN 2 THEN N'NVIDIA Tesla Data Center Accelerator'
                WHEN 3 THEN N'NVIDIA DRIVE Automotive Computing'
                ELSE N'NVIDIA Omniverse Enterprise Platform'
            END
        ELSE 
            CASE (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 4)
                WHEN 0 THEN N'NVIDIA Jetson Edge AI Computing Platform'
                WHEN 1 THEN N'NVIDIA DRIVE AGX Autonomous Vehicle'
                WHEN 2 THEN N'NVIDIA Clara Healthcare AI Platform'
                ELSE N'NVIDIA Metropolis Smart City Solutions'
            END
    END, -- ZTOPLVLNAME (41 chars max)
    CASE (ROW_NUMBER() OVER (ORDER BY MATERIAL) % 3) WHEN 0 THEN N'VIRTUAL_KIT' WHEN 1 THEN N'PHYSICAL_KIT' ELSE N'HYBRID_KIT' END, -- ZVIRTUALKIT
    N'SYS_USER_' + CAST((ROW_NUMBER() OVER (ORDER BY MATERIAL) % 10) + 1 AS NVARCHAR), -- LASTMODIFIEDBY (14 chars max)
    FORMAT(DATEADD(day, -(ROW_NUMBER() OVER (ORDER BY MATERIAL) % 30), GETDATE()), 'yyyy-MM-dd'), -- LASTMODIFIEDDATE
    N'SYS_USR_' + CAST((ROW_NUMBER() OVER (ORDER BY MATERIAL) % 10) + 1 AS NVARCHAR), -- CREATEDBY (12 chars max)
    FORMAT(DATEADD(day, -(ROW_NUMBER() OVER (ORDER BY MATERIAL) % 90), GETDATE()), 'yyyy-MM-dd') -- CREATEDDATE

FROM hana_material_master;

PRINT 'Inserted ' + CAST(@@ROWCOUNT AS NVARCHAR) + ' records into brz_lnd_IBP_Product_Master';

-- =====================================================
-- VALIDATION: Check PRDID Matching Distribution
-- =====================================================

PRINT '';
PRINT 'PRDID Matching Analysis:';

SELECT 
    'EXACT_MATCH' as MatchType,
    COUNT(*) as RecordCount,
    CAST(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM brz_lnd_IBP_Product_Master) AS DECIMAL(5,1)) as Percentage
FROM brz_lnd_IBP_Product_Master ibp
INNER JOIN hana_material_master hmm ON ibp.PRDID = hmm.MATERIAL

UNION ALL

SELECT 
    'PREFIX_MATCH' as MatchType,
    COUNT(*) as RecordCount,
    CAST(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM brz_lnd_IBP_Product_Master) AS DECIMAL(5,1)) as Percentage
FROM brz_lnd_IBP_Product_Master ibp
INNER JOIN hana_material_master hmm ON ibp.PRDID = N'PRD_' + hmm.MATERIAL

UNION ALL

SELECT 
    'NO_MATCH' as MatchType,
    COUNT(*) as RecordCount,
    CAST(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM brz_lnd_IBP_Product_Master) AS DECIMAL(5,1)) as Percentage
FROM brz_lnd_IBP_Product_Master ibp
WHERE ibp.PRDID LIKE N'NOMATCH_%';

PRINT '';
PRINT 'Sample PRDID values:';

SELECT TOP 10 
    hmm.MATERIAL as HMM_Material,
    ibp.PRDID as IBP_PRDID,
    CASE 
        WHEN ibp.PRDID = hmm.MATERIAL THEN 'EXACT_MATCH'
        WHEN ibp.PRDID = N'PRD_' + hmm.MATERIAL THEN 'PREFIX_MATCH'
        WHEN ibp.PRDID LIKE N'NOMATCH_%' THEN 'NO_MATCH'
        ELSE 'OTHER'
    END as MatchType
FROM hana_material_master hmm
LEFT JOIN brz_lnd_IBP_Product_Master ibp ON ibp.ZBASEMATERIAL = hmm.MATERIAL
ORDER BY hmm.MATERIAL;

PRINT '';
PRINT '=====================================================';
PRINT 'IBP PRODUCT MASTER PRDID MATCHING COMPLETED!';
PRINT '70% Exact Match, 20% Prefix Match, 10% No Match';
PRINT '=====================================================';

SET NOCOUNT OFF;
