#!/bin/bash
# Example usage scripts for standalone_sql_preview.py

echo "🚀 Standalone SQL Preview - Example Usage"
echo "=========================================="

# Set your database connection details
DB_HOST="your-sql-server"
DB_PORT="1433"
DB_NAME="your-database"
DB_USER="your-username"
DB_PASSWORD="your-password"
SCHEMA="newdqnov7"
OPENAI_KEY="your-openai-api-key"

echo ""
echo "📋 Example 1: Basic LLM-based SQL Generation"
echo "============================================="
echo "python standalone_sql_preview.py \\"
echo "  --nl-definition \"get products from hana_material_master where OPS_PLANNER is missing\" \\"
echo "  --kg-name \"New_KG_101\" \\"
echo "  --select-schema \"$SCHEMA\" \\"
echo "  --openai-key \"$OPENAI_KEY\" \\"
echo "  --temperature 0.7 \\"
echo "  --db-host \"$DB_HOST\" \\"
echo "  --db-port $DB_PORT \\"
echo "  --db-name \"$DB_NAME\" \\"
echo "  --db-user \"$DB_USER\" \\"
echo "  --db-password \"$DB_PASSWORD\" \\"
echo "  --use-llm \\"
echo "  --verbose"

echo ""
echo "📋 Example 2: Rule-based Generation (No LLM)"
echo "============================================="
echo "python standalone_sql_preview.py \\"
echo "  --nl-definition \"find missing planners in hana_material_master\" \\"
echo "  --select-schema \"$SCHEMA\" \\"
echo "  --db-host \"$DB_HOST\" \\"
echo "  --db-name \"$DB_NAME\" \\"
echo "  --db-user \"$DB_USER\" \\"
echo "  --db-password \"$DB_PASSWORD\" \\"
echo "  --output-format pretty"

echo ""
echo "📋 Example 3: JSON Output for Integration"
echo "========================================="
echo "python standalone_sql_preview.py \\"
echo "  --nl-definition \"get products from hana_material_master and brz_lnd_SAR_Excel_NBU where planner is missing in both\" \\"
echo "  --kg-name \"New_KG_101\" \\"
echo "  --select-schema \"$SCHEMA\" \\"
echo "  --openai-key \"$OPENAI_KEY\" \\"
echo "  --temperature 0.3 \\"
echo "  --db-host \"$DB_HOST\" \\"
echo "  --db-name \"$DB_NAME\" \\"
echo "  --db-user \"$DB_USER\" \\"
echo "  --db-password \"$DB_PASSWORD\" \\"
echo "  --use-llm \\"
echo "  --output-format json"

echo ""
echo "📋 Example 4: SQL-only Output (for piping)"
echo "==========================================="
echo "python standalone_sql_preview.py \\"
echo "  --nl-definition \"show all products with missing OPS_PLANNER\" \\"
echo "  --select-schema \"$SCHEMA\" \\"
echo "  --db-host \"$DB_HOST\" \\"
echo "  --db-name \"$DB_NAME\" \\"
echo "  --db-user \"$DB_USER\" \\"
echo "  --db-password \"$DB_PASSWORD\" \\"
echo "  --output-format sql-only > generated_query.sql"

echo ""
echo "📋 Example 5: Using Environment Variables"
echo "=========================================="
echo "export OPENAI_API_KEY=\"$OPENAI_KEY\""
echo "python standalone_sql_preview.py \\"
echo "  --nl-definition \"find products where marketing code is missing\" \\"
echo "  --select-schema \"$SCHEMA\" \\"
echo "  --db-host \"$DB_HOST\" \\"
echo "  --db-name \"$DB_NAME\" \\"
echo "  --db-user \"$DB_USER\" \\"
echo "  --db-password \"$DB_PASSWORD\" \\"
echo "  --use-llm"

echo ""
echo "🔧 Setup Instructions:"
echo "======================"
echo "1. Install dependencies:"
echo "   pip install -r standalone_requirements.txt"
echo ""
echo "2. Update the variables at the top of this script with your actual values:"
echo "   - DB_HOST: Your SQL Server hostname"
echo "   - DB_NAME: Your database name"
echo "   - DB_USER: Your database username"
echo "   - DB_PASSWORD: Your database password"
echo "   - SCHEMA: Your schema name (e.g., 'newdqnov7')"
echo "   - OPENAI_KEY: Your OpenAI API key"
echo ""
echo "3. Make this script executable:"
echo "   chmod +x example_usage.sh"
echo ""
echo "4. Run examples:"
echo "   ./example_usage.sh"
echo ""
echo "🎉 Ready to use!"
