import React from 'react';
import {
  Box,
  Typography,
  Paper,
  Grid,
  LinearProgress
} from '@mui/material';

function HintsStatistics({ statistics }) {
  if (!statistics) {
    return null;
  }

  const completionPercentage = statistics.total_columns > 0
    ? Math.round((statistics.manual_verified / statistics.total_columns) * 100)
    : 0;

  const autoGeneratedPercentage = statistics.total_columns > 0
    ? Math.round((statistics.auto_generated / statistics.total_columns) * 100)
    : 0;

  return (
    <Paper sx={{ p: 3 }}>
      <Typography variant="h6" gutterBottom>
        Hints Statistics
      </Typography>

      <Grid container spacing={3}>
        <Grid item xs={12}>
          <Typography variant="body2" color="text.secondary" gutterBottom>
            Manual Verification Progress
          </Typography>
          <Box display="flex" alignItems="center" gap={2}>
            <Box sx={{ flex: 1 }}>
              <LinearProgress
                variant="determinate"
                value={completionPercentage}
                sx={{ height: 10, borderRadius: 5 }}
              />
            </Box>
            <Typography variant="body2" fontWeight="bold">
              {completionPercentage}%
            </Typography>
          </Box>
          <Typography variant="caption" color="text.secondary">
            {statistics.manual_verified} of {statistics.total_columns} columns verified
          </Typography>
        </Grid>

        <Grid item xs={12}>
          <Typography variant="body2" color="text.secondary" gutterBottom>
            Auto-Generated Hints
          </Typography>
          <Box display="flex" alignItems="center" gap={2}>
            <Box sx={{ flex: 1 }}>
              <LinearProgress
                variant="determinate"
                value={autoGeneratedPercentage}
                color="info"
                sx={{ height: 10, borderRadius: 5 }}
              />
            </Box>
            <Typography variant="body2" fontWeight="bold">
              {autoGeneratedPercentage}%
            </Typography>
          </Box>
          <Typography variant="caption" color="text.secondary">
            {statistics.auto_generated} of {statistics.total_columns} columns auto-generated
          </Typography>
        </Grid>

        <Grid item xs={12} md={6}>
          <Typography variant="caption" color="text.secondary">Last Updated</Typography>
          <Typography variant="body2">
            {statistics.last_updated
              ? new Date(statistics.last_updated).toLocaleString()
              : 'N/A'}
          </Typography>
        </Grid>

        <Grid item xs={12} md={6}>
          <Typography variant="caption" color="text.secondary">Updated By</Typography>
          <Typography variant="body2">{statistics.updated_by || 'N/A'}</Typography>
        </Grid>

        <Grid item xs={12}>
          <Typography variant="caption" color="text.secondary">Total Manual Edits</Typography>
          <Typography variant="body2">{statistics.manual_edits || 0}</Typography>
        </Grid>
      </Grid>
    </Paper>
  );
}

export default HintsStatistics;
