apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kg-builder-graphiti-storage
  namespace: cognito-ai-dq-dev
  labels:
    app: kg-builder-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kg-builder-data-storage
  namespace: cognito-ai-dq-dev
  labels:
    app: kg-builder-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
